/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue';

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('antdv-next')['Alert']
    AAvatar: typeof import('antdv-next')['Avatar']
    ABreadcrumb: typeof import('antdv-next')['Breadcrumb']
    ABreadcrumbItem: typeof import('antdv-next')['BreadcrumbItem']
    AButton: typeof import('antdv-next')['Button']
    ACard: typeof import('antdv-next')['Card']
    ACol: typeof import('antdv-next')['Col']
    AColorPicker: typeof import('antdv-next')['ColorPicker']
    AConfigProvider: typeof import('antdv-next')['ConfigProvider']
    ADivider: typeof import('antdv-next')['Divider']
    ADrawer: typeof import('antdv-next')['Drawer']
    ADropdown: typeof import('antdv-next')['Dropdown']
    AEmpty: typeof import('antdv-next')['Empty']
    AForm: typeof import('antdv-next')['Form']
    AFormItem: typeof import('antdv-next')['FormItem']
    AInput: typeof import('antdv-next')['Input']
    AInputPassword: typeof import('antdv-next')['InputPassword']
    ALayout: typeof import('antdv-next')['Layout']
    ALayoutContent: typeof import('antdv-next')['LayoutContent']
    ALayoutSider: typeof import('antdv-next')['LayoutSider']
    AMenu: typeof import('antdv-next')['Menu']
    AResult: typeof import('antdv-next')['Result']
    ARow: typeof import('antdv-next')['Row']
    ASpace: typeof import('antdv-next')['Space']
    AStatistic: typeof import('antdv-next')['Statistic']
    ASwitch: typeof import('antdv-next')['Switch']
    ATable: typeof import('antdv-next')['Table']
    ATag: typeof import('antdv-next')['Tag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spinner: typeof import('./src/components/spinner/index.vue')['default']
  }
}

// For TSX support
declare global {
  const AAlert: (typeof import('antdv-next'))['Alert'];
  const AAvatar: (typeof import('antdv-next'))['Avatar'];
  const ABreadcrumb: (typeof import('antdv-next'))['Breadcrumb'];
  const ABreadcrumbItem: (typeof import('antdv-next'))['BreadcrumbItem'];
  const AButton: (typeof import('antdv-next'))['Button'];
  const ACard: (typeof import('antdv-next'))['Card'];
  const ACol: (typeof import('antdv-next'))['Col'];
  const AColorPicker: (typeof import('antdv-next'))['ColorPicker'];
  const AConfigProvider: (typeof import('antdv-next'))['ConfigProvider'];
  const ADivider: (typeof import('antdv-next'))['Divider'];
  const ADrawer: (typeof import('antdv-next'))['Drawer'];
  const ADropdown: (typeof import('antdv-next'))['Dropdown'];
  const AEmpty: (typeof import('antdv-next'))['Empty'];
  const AForm: (typeof import('antdv-next'))['Form'];
  const AFormItem: (typeof import('antdv-next'))['FormItem'];
  const AInput: (typeof import('antdv-next'))['Input'];
  const AInputPassword: (typeof import('antdv-next'))['InputPassword'];
  const ALayout: (typeof import('antdv-next'))['Layout'];
  const ALayoutContent: (typeof import('antdv-next'))['LayoutContent'];
  const ALayoutSider: (typeof import('antdv-next'))['LayoutSider'];
  const AMenu: (typeof import('antdv-next'))['Menu'];
  const AResult: (typeof import('antdv-next'))['Result'];
  const ARow: (typeof import('antdv-next'))['Row'];
  const ASpace: (typeof import('antdv-next'))['Space'];
  const AStatistic: (typeof import('antdv-next'))['Statistic'];
  const ASwitch: (typeof import('antdv-next'))['Switch'];
  const ATable: (typeof import('antdv-next'))['Table'];
  const ATag: (typeof import('antdv-next'))['Tag'];
  const RouterLink: (typeof import('vue-router'))['RouterLink'];
  const RouterView: (typeof import('vue-router'))['RouterView'];
  const Spinner: (typeof import('./src/components/spinner/index.vue'))['default'];
}
